FunctionTypeUtils test for NPE
Related to https://stackoverflow.com/questions/72163534/spring-batch-integration-throwns-org-springframework-messaging-messagehandlingex

The `FunctionTypeUtils.isMessage()` fails with NPE
when target method has non-message argument with generic parameter.
Even if we instantiate the class with specific generic argument,
that info is not available for reflection and `MethodParameter`
end up with a generic parameter name which is essentially a `TypeVariable`

The stacktrace is like this:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getGenericInterfaces()" because "targetType" is null

	at net.jodah.typetools.TypeResolver.getTypeVariableMap(TypeResolver.java:494)
	at net.jodah.typetools.TypeResolver.resolveRawClass(TypeResolver.java:387)
	at net.jodah.typetools.TypeResolver.resolveRawClass(TypeResolver.java:373)
	at org.springframework.cloud.function.context.catalog.FunctionTypeUtils.isMessage(FunctionTypeUtils.java:416)
```